### ISSUE TITLE
Factorial Program in Java

### ISSUE THREAD

**Issue by MansiBhayade** [dimpeshpanwar/javabasicprograms#56]
@dimpeshpanwar I want to write factorial program in java for hacktoberfest2023 contribution. Can you please assign this issue to me

**Comment by MansiBhayade** [comment]
@dimpeshpanwar Can you please assign labels, it is not shown in my contribution profile

**Comment by dimpeshpanwar** [comment]
Done...

**Comment by mansidhote** [comment]
Hey @dimpeshpanwar ,Can you please assign it to me .

**Comment by dimpeshpanwar** [comment]
Done
